org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties (?? 26.1.2 ????)
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16.1

# Mod Properties
mod_version=1.0.0
maven_group=com.exxxee.backpack

# Dependencies
fabric_api_version=0.149.0+26.1.2
